### ISSUE TITLE
Hawaii's 2024 Week 0 matchup is incorrect.

### ISSUE THREAD

**Issue by jacobhaft** [CFBD/cfbd-python#11]
I don't know if this is really an "issue", but using the get_games(2024, division='fbs') still shows Hawaii's week one matchup as against Oregon, when that game has been scrapped and it has been [replaced](https://www.instagram.com/reel/C34O8SNPbPY/?utm_source=ig_embed) with Delaware State @ Hawaii. It also looks to be missing New Mexico's and SMU's week one matchup, but it has Florida State's. I think I'm literally the only human on Earth who cares about this.

**Comment by BlueSCar** [comment]
These should all be corrected now
