### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by salcedam** [CFBD/cfbd-python#9]
When attempting to pull data using the Stats API _get_advanced_team_game_stats_ function, I am getting a 504 Gateway Timeout error. Other API calls like _get_lines_ from the Bets API and _get_games_ call from the Games API work just fine.

**Comment by easella** [comment]
sometimes the games_api has a 504 timeout. Just try it in a little bit and it'll work fine. I don't think the people who maintain this repository are looking at the "issues" tab.

**Comment by BlueSCar** [comment]
This repo is auto-generated. The best way to reach out is via one of the methods listed on the website. 504 Gateway Timeouts are intermittent, but have been drastically cut down in recent seasons.
